spring:
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always
  application:
    name: listing-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      # TODO: change later to: ddl-auto: validate
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}


management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: listing-service
    version: "@project.version@"

server:
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true
    whitelabel:
      enabled: false

# for swagger docs
springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    path: /docs

