CREATE TABLE listings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    price       DECIMAL,
    city        VARCHAR(255),
    status      VARCHAR(255),
    owner_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_listings PRIMARY KEY (id)
);

CREATE TABLE user_favorite_listing
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    listing_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_favorite_listing PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    keycloak_id VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_favorite_listing
    ADD CONSTRAINT uc_9aa3e027392a3a4a1e669697a UNIQUE (user_id, listing_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_keycloak UNIQUE (keycloak_id);

ALTER TABLE listings
    ADD CONSTRAINT FK_LISTINGS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE user_favorite_listing
    ADD CONSTRAINT FK_USER_FAVORITE_LISTING_ON_LISTING FOREIGN KEY (listing_id) REFERENCES listings (id);

ALTER TABLE user_favorite_listing
    ADD CONSTRAINT FK_USER_FAVORITE_LISTING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);