name: Build & Test (Listing Service)

# Trigger workflow on pushes to master/develop, pull requests, or manual trigger
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: 'maven'  # enable Maven caching

      # Run Maven build & tests (Testcontainers run automatically)
      - name: Build & Test
        run: mvn clean verify -Dspring.profiles.active=test

      # Upload test reports for inspection in Actions UI
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
