name: Listing Service CI/CD

# Triggers
on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'release/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  ##########################
  # Build Job
  ##########################
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      # Set Version for Maven & Docker
      - name: Set Docker version
        id: set_version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/release/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/release/}"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            VERSION="${BRANCH_NAME}-${GITHUB_SHA:0:7}"
          fi
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT  # <-- Job Output für andere Jobs

      - name: Build JAR
        run: mvn clean package -Drevision=${{ steps.set_version.outputs.version }} -DskipTests -B

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: listing-service-jar
          path: target/*.jar

  ##########################
  # Tests Job
  ##########################
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: listing-service-jar
          path: target/

      - name: Run Maven Tests
        run: mvn verify -Dspring.profiles.active=test -B

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

  ##########################
  # Docker Build & Push Job
  ##########################
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [ tests, build ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: listing-service-jar
          path: target/

      - name: Build & Tag Docker Image
        run: |
          IMAGE_NAME="baris1892/private"
          IMAGE_TAG="listing-service-${{ needs.build.outputs.version }}" 
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - name: Push Docker Image
        run: |
          IMAGE_NAME="baris1892/private"
          IMAGE_TAG="listing-service-${{ needs.build.outputs.version }}"
          docker push ${IMAGE_NAME}:${IMAGE_TAG}

  ##########################
  # Deploy Job (Dummy for local k3s)
  ##########################
  deploy:
    name: Deploy to k3s (Dummy)
    runs-on: ubuntu-latest
    needs: [ docker, build ]
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/')

    steps:
      - name: Dummy Deploy
        run: |
          echo "kubectl apply -f k8s/deployment.yaml with image: baris1892/private:${{ needs.build.outputs.version }}"
          echo "Skipping actual deployment (local cluster)"
