name: Listing Service CI/CD

# Triggers
on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'release/*'       # release trigger
  pull_request:
    branches:
      - main
  workflow_dispatch:       # manual trigger

jobs:

  ##########################
  # Build Job
  ##########################
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Set project version
        id: set_version
        run: |
          if [[ "${GITHUB_REF_NAME}" == release/* ]]; then
            VERSION=${GITHUB_REF_NAME#release/}
          else
            VERSION="snapshot-${GITHUB_SHA::7}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Project version: $VERSION"

      - name: Build JAR
        run: mvn clean package -Drevision=${{ env.VERSION }} -DskipTests -B

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: listing-service-jar
          path: target/*.jar

  ##########################
  # Run Tests
  ##########################
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: listing-service-jar
          path: target/

      # Run Maven tests (Testcontainers run automatically)
      - name: Run Tests
        run: mvn verify -Dspring.profiles.active=test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

  ##########################
  # Docker Build & Push Job
  ##########################
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [ build, tests ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: listing-service-jar
          path: target/

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:latest

  ##########################
  # Deploy Job (Dummy for local k3s)
  ##########################
  deploy:
    name: Deploy to k3s (Dummy)
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/')

    steps:
      - name: Dummy Deploy
        run: |
          echo "kubectl apply -f k8s/deployment.yaml with image: ${{ secrets.DOCKERHUB_USERNAME }}/listing-service:${{ env.VERSION }}"
          echo "Skipping actual deployment (local cluster)"
